config/routes.rb
Rails.application.routes.draw do

  resources :cities

  root 'cities#index'

  get 'sign_up' => 'users#sign_up'
  post 'sign_up' => 'users#create'

  get 'properties/new' => 'properties#new'
  post 'properties/new' => 'properties#create'

  get 'sign_in' => 'users#sign_in'
  post 'sign_in' => 'users#authenticate'


end

app/models/city.rb
class City < ActiveRecord::Base

  validates :name, presence: true
  validates :state, length: {is: 2}

end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user

  validates :title, :description, :price, :user,
    presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  belongs_to :city

  validates :name, :birth_date, :phone, :username, :password, :city,
    presence: true
  validates :username, uniqueness: true
  validates :password, confirmation: true, length: {minimum: 6}

  def self.authenticate(params)
    user = find_by(username: params[:username])
    if user
      return user if user.password == params[:password]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_authentication
    if !logged?
      redirect_to root_path, alert: 'Precisa estar logado!'
    end
  end

  def logged?
    session[:user_id].present?
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :state)
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  before_action :require_authentication

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    @property.user_id = session[:user_id]
    if @property.save
      redirect_to root_path, notice: 'Criado com sucesso'
    else
      render :new
    end
  end

  private

  def property_params
    params.require(:property).permit(:title, :description,
      :price)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def sign_up
    @user = User.new
    @cities = City.order(:name).all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to cities_path
    else
      @cities = City.order(:name).all
      render :sign_up
    end
  end

  def sign_in
    @user = User.new
  end

  def authenticate
    user = User.authenticate(authenticate_params)
    if user
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logado com sucesso!'
    else
      @user = User.new
      @message = 'Falha na autenticação'
      render :sign_in
    end
  end

  private

  def authenticate_params
    params.require(:user).permit(:username, :password)
  end

  def user_params
    params.require(:user).
      permit(:name, :phone, :birth_date, :username,
        :password, :city_id, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<h1>Listing Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.state %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @city.state %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImobRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <%= link_to root_path do %>
    <h2>IMOB RAILS</h2>
  <% end %>

  <span>
    <%= link_to 'Fazer login', sign_in_path %>
    <%= link_to 'Cadastre-se', sign_up_path %>
  </span>
</header>

<main>
  <%= yield %>
</main>

</body>
</html>

app/views/properties/new.html.erb
<h1>Cadastre seu imovel</h1>


<%= form_for @property, url: properties_new_path do |f| %>

    <% if @property.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@property.errors.count, "error") %> foram encontrados</h2>

          <ul>
          <% @property.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
    <% end %>

    <div>
        <%= f.label :title, 'Titulo' %>
        <%= f.text_field :title %>
    </div>


    <div>
        <%= f.label :description, 'Descrição' %>
        <%= f.text_field :description %>
    </div>

    <div>
        <%= f.label :price, 'Preço' %>
        <%= f.text_field :price %>
    </div>

    <div>
        <%= f.submit %>
    </div>
<% end %>

app/views/users/sign_in.html.erb
<h1>Autenticação</h1>


<%= form_for @user, url: sign_in_path do |f| %>

    <% if @message %>
      <div class="alert">
        <%= @message %>
      </div>
    <% end %>

    <div>
        <%= f.label :username, 'Usuário' %>
        <%= f.text_field :username %>
    </div>

    <div>
        <%= f.label :password, 'Senha' %>
        <%= f.password_field :password %>
    </div>

    <div>
      <%= f.submit 'Entrar' %>
    </div>

<% end %>

app/views/users/sign_up.html.erb
<h1>Cadastra-se</h1>


<%= form_for @user, url: '/sign_up' do |f| %>

    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> foram encontrados</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
    <% end %>

    <div>
        <%= f.label :name, 'Nome' %>
        <%= f.text_field :name %>
    </div>

    <div>
    <%# teste  %>
        <%= f.label :birth_date, 'Data de nascimento' %>
        <%= f.date_select :birth_date, start_year: Date.today.year - 100 %>
    </div>

    <div>
        <%= f.label :city_id, 'Cidade' %>
        <%= f.collection_select :city_id, City.all, :id, :name %>
    </div>

    <div>
        <%= f.label :phone, 'Telefone' %>
        <%= f.text_field :phone %>
    </div>

    <div>
        <%= f.label :username, 'Usuario' %>
        <%= f.text_field :username %>
    </div>

    <div>
        <%= f.label :password, 'Senha' %>
        <%= f.password_field :password %>
    </div>

    <div>
        <%= f.label :password_confirmation, 'Confirme sua senha' %>
        <%= f.password_field :password_confirmation %>
    </div>

    <div>
        <%= f.submit %>
    </div>
<% end %>